table 'Risk Threshold'
	lineageTag: 7c70a453-a148-48f7-ac1c-3a0e7a70b88d

	measure 'Risk Threshold Value' = SELECTEDVALUE('Risk Threshold'[Risk Threshold], 0.35)
		lineageTag: 44d14e57-3030-4f14-a9ff-ac2f615c0a0b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Risk Threshold'
		lineageTag: f4c26672-eaff-4e3a-a8bf-dd30a1134d77
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Risk Threshold' = calculated
		mode: import
		source = GENERATESERIES(0.1, 0.9, 0.05)

	annotation PBI_Id = 5e6d92214cb44f46a292b27b775b5076

